backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
    - name: "events"
      label: "Events"
      folder: "events"
      create: true
      slug: "{{slug}}"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Performer", name: "performer", widget: "string", optional: true}
        - {label: "Abstract", name: "abstract", widget: "text"}
        - {label: "Image", name: "image", widget: "image", optional: true}
        - {label: "Author", name: "author", widget: "string"}
        - {label: "Date", name: "date", widget: "datetime"}
        - {label: "Body", name: "body", widget: "markdown"}
